version: 2.1

jobs:
  lint:
    docker:
      - image: hashicorp/terraform:0.12.26
    steps:
      - checkout
      - run:
          name: Init
          command: terraform init -backend=false
      - run:
          name: Lint
          command: terraform fmt -check=true -diff=true -recursive
      - run:
          name: Validate
          command: terraform validate
workflows:
  version: 2
  primary:
    jobs:
      - lint
